### ISSUE TITLE
RFC: Include no-console rule

### ISSUE THREAD

**Issue by mvarendorff** [atmina/linting#75]
`console.log` is commonly used in our code to throw in quick and dirty debugging. However it is sometimes forgotten to be removed.

We make frequent use of `console.warn`, `console.error` in different places in our web applications for development messages. We also use `console.info` in CLI scripts to print progress output.

I thus propose adding `no-console: ["error", { allow: ["info", "warn", "error"] }]` to our base configuration in order to reduce the chances of debugging `console` statements making it to production.

**Comment by reiv** [comment]
Sounds good to me, PR is up.
