### ISSUE TITLE
RFC: Remove eslint-plugin-prettier

### ISSUE THREAD

**Issue by mvarendorff** [atmina/linting#88]
Prettier themselves mention using `eslint-plugin-prettier` as not recommended here: https://prettier.io/docs/en/integrating-with-linters.html#notes

Generally we should reserve prettier for formatting and ESLint for everything else. With the Prettier plugin, ESLint is also run as formatter which is rather slow. This is especially annoying when having `eslint --fix` run on save which then very slowly starts to format things. Then seeing the quick flash of prettier afterwards, reminding you at this could all have been done a lot quicker.

It also isolates issues in the CI more clearly (so a formatting issue doesn't automatically fail two jobs instead of one).

**Comment by reiv** [comment]
I'm not opposed to this. I haven't run into the performance issues you described, but there are additional benefits to separating those steps. For example, Prettier can also format things which aren't JS/TS, such as GraphQL, CSS, and possibly YAML.
